package com.cache.second;
// Generated 3 Dec, 2016 9:28:05 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Hemployee generated by hbm2java
 */
public class Hemployee implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private BigDecimal salary;

	public Hemployee() {
	}

	public Hemployee(String fname, String lname, BigDecimal salary) {
		this.fname = fname;
		this.lname = lname;
		this.salary = salary;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@Override
	public String toString() {
		return "Hemployee [id=" + id + ", fname=" + fname + ", lname=" + lname + ", salary=" + salary + "]";
	}
	
	

}
